version: "3"

services:
  service:
    image: rest-service
    container_name: rest-service
    build:
      context: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - "db"
    restart: always
    env_file:
      - .env
    networks:
      - custom-network
    volumes:
      - ./src:/app/src    
      - nodemodules:/app/node_modules
      - ./logs:/app/logs
  db:
    image: postgres-db
    container_name: postgres-db
    build:
      context: ./database/
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - custom-network
    volumes:
      - postgres_db:/var/lib/postgresql/data
  
networks:
  custom-network:
    driver: bridge
    # ipam:
    #   config:
    #     - subnet: 0.0.0.0/4

volumes:
  nodemodules:
  postgres_db:
