version: "3"

services:
  nestjs_app:
    image: nestjs_app
    container_name: nestjs_app
    build:
      context: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - "nestjs_db"
    restart: always
    env_file:
      - .env
    networks:
      - custom-network
    volumes:
      - ./src:/app/src    
      - nodemodules:/app/node_modules
      - logs:/app/logs
  nestjs_db:
    image: postgres_db
    container_name: postgres_db
    build:
      context: ./database/
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - custom-network
    volumes:
      - postgres_db:/var/lib/postgresql/data
  
networks:
  custom-network:
    driver: bridge

volumes:
  nodemodules:
  logs:
  postgres_db:
