version: "3"

services:
  service:
    image: rest-service
    container_name: rest-service
    build:
      context: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - "db"
    restart: always
    env_file:
      - .env
    networks:
      - custom-network
  db:
    image: postgres-db
    container_name: postgres-db
    build:
      context: ./database/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - custom-network
  
networks:
  custom-network:
    driver: bridge